//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : banco_teste
	/// Data Source    : database-1.crmrsizpasfs.sa-east-1.rds.amazonaws.com
	/// Server Version : 8.0.29
	/// </summary>
	public partial class BancoTesteDB : LinqToDB.Data.DataConnection
	{
		public ITable<Carro> Carro { get { return this.GetTable<Carro>(); } }

		public BancoTesteDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public BancoTesteDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public BancoTesteDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public BancoTesteDB(LinqToDBConnectionOptions<BancoTesteDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("carro")]
	public partial class Carro
	{
		[Column("idcarro"), PrimaryKey, Identity] public int    Idcarro { get; set; } // int
		[Column("modelo"),  NotNull             ] public string Modelo  { get; set; } // varchar(60)
		[Column("placa"),   NotNull             ] public string Placa   { get; set; } // varchar(60)
		[Column("chassi"),  NotNull             ] public string Chassi  { get; set; } // varchar(60)
		[Column("ano"),     NotNull             ] public int    Ano     { get; set; } // int
		[Column("marca"),   NotNull             ] public string Marca   { get; set; } // varchar(45)
	}

	public static partial class TableExtensions
	{
		public static Carro Find(this ITable<Carro> table, int Idcarro)
		{
			return table.FirstOrDefault(t =>
				t.Idcarro == Idcarro);
		}
	}
}
